version: '3'
services:
  web:
    build: .
    ports:
      - "8443:8443"
    depends_on:
      - mongodb
      - mongoTEST
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "admin1"
  mongoTEST:
    image: mongo
    ports:
      - "27016:27017"