spring:
  data:
    mongodb:
      username: mongoadmin
      password: admin1
      authentication-database: admin

facebook:
  client:
    clientId: 226509771534684
    clientSecret: 4c29a748d8777b72a03e079449c13f08
    accessTokenUri: https://graph.facebook.com/v3.1/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/v3.1/dialog/oauth
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/v3.1/me?fields=id,email,birthday,first_name,last_name

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
    key-store-type: JKS