spring:
  data:
    mongodb:
      username: mongoadmin
      password: admin1
      authentication-database: admin

facebook:
  client:
    clientId: 226509771534684
    clientSecret: 4c29a748d8777b72a03e079449c13f08
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

security:
  oauth2:
    client:
      client-id: diemy
      client-secret: diemy2secret
      scope: read,write
      auto-approve-scopes: '.*'